headers:
  User-Agent: Android
  Connection: keep-alive
  platform: Android
  bundle: com.btiming.demo
  platform-v: 1.1.3.11
  platform-model: Nexus 6P
  platform-brand: google
  client-v: 1.7.2
  device-id: a6475416-403a-4408-878c-d683fb1ae377
  network-type: wifi
  sid: u02-b0feee7b-2ea1-4bc0-b9fe-a8c5509e85e1
  lan: en
  uid:
  country: HK
  debug: Kuaiyin@123
  timeZone: !!str -300
import_str:
  - import pytest
  - import allure
  - import requests
  - from Core.BaseApi import ApiRequest
  - request = ApiRequest()
  - from Core.Logging import logger
  - import json
  - from Core.common import yaml_load
switch: Debug
#switch: True