loggings:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s - %(process)s - %(filename)s -%(funcName)s- %(levelname)s - %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            level: ERROR
            formatter: simple
            stream: ext://sys.stdout
        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: C:\Users\67091\Desktop\MCAutTest\LogFiles\info.log
            maxBytes: 10485760 # 10MB
            backupCount: 20
            encoding: utf8
        error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: C:\Users\67091\Desktop\MCAutTest\LogFiles\errors.log
            maxBytes: 10485760 # 10MB
            backupCount: 20
            encoding: utf8
    loggers:
        my_module:
            level: ERROR
            handlers: [console]
            propagate: no
    root:
        level: INFO
        handlers: [console, info_file_handler]

driver_options:
    - disable-infobars
    - --start-maximized
    #- --headless
driver_path: DriverExe
outtime: 20
POLL_FREQUENCY: 0.5



